### ISSUE TITLE
TODO - Use Auth0 JWT for auth between app and api

### ISSUE THREAD

**Issue by christopherreay** [christopherreay/quickDocsDelNorte#2]
* [x] grant Chris access to the Auth0 tennant
* [ ] add JWT as a header to API request from the react
* [ ] add Auth0 AuthorizationClient to the API to check every request
